services:
    database:
        image: postgres
        container_name: APIprisma
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=APIprisma
        volumes:
            - pgdata:/data/postgres

volumes:
    pgdata:
        driver: local